# ----
# Site

<<<<<<< HEAD
title: Jacob Chartrand
=======
title: Aperture Template
>>>>>>> 01c696a9e32cd510f05cac44870084e31b00be89
url: "https://cosmic-hippopotamus.cloudvent.net"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Photography portfolio template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Aperture Template
  links:
    - https://github.com/CloudCannon/aperture-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
<<<<<<< HEAD
      image: /uploads/01.jpg
=======
      image: /uploads/1.jpg
>>>>>>> 01c696a9e32cd510f05cac44870084e31b00be89
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
<<<<<<< HEAD
    expandable: true
=======
    expandable: true
>>>>>>> 01c696a9e32cd510f05cac44870084e31b00be89
